export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig/:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$HOME/.local/lib/:$LD_LIBRARY_PATH
export  C_INCLUDE_PATH=$HOME/.local/include/:$C_INCLUDE_PATH
export PATH="$HOME/magick/bin:/opt/nvim-linux-x86_64/bin:/usr/local/sbin:$PATH"
if ! hostname | grep "\.cloudlab\.us$"; then
  export PATH="$HOME/go/bin:$PATH"
  . "$HOME/.cargo/env"
  . "$HOME/.ghcup/env"
fi
export BROWSER="/mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe"
export S6="${HOME}/.local/share/s6"
export PATH="$PATH:/opt/nvim-linux64/bin"

export CF_USERNAME=atewari

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/tewaro/google-cloud-sdk/path.zsh.inc' ]; then . '/home/tewaro/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/tewaro/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/tewaro/google-cloud-sdk/completion.zsh.inc'; fi


