export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig/:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$HOME/.local/lib/:$LD_LIBRARY_PATH
export  C_INCLUDE_PATH=$HOME/.local/include/:$C_INCLUDE_PATH
export PATH="/opt/nvim-linux64/bin:/usr/local/sbin:$PATH"
if ! hostname | grep "\.cloudlab\.us$"; then
  export PATH="$HOME/go/bin:$PATH"
  . "$HOME/.cargo/env"
  . "$HOME/.ghcup/env"
fi
export BROWSER="/mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe"
export S6="${HOME}/.local/share/s6"
